// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v5.27.1
// source: gateway_service.proto

package gateway

import (
	_go "golang_restapi/contracts/common/go"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_gateway_service_proto protoreflect.FileDescriptor

const file_gateway_service_proto_rawDesc = "" +
	"\n" +
	"\x15gateway_service.proto\x12\agateway\x1a\x1cgoogle/api/annotations.proto\x1a\x13common/common.proto\x1a\x1bgateway/gateway_model.proto2\xf0\t\n" +
	"\aGateway\x12a\n" +
	"\bRegister\x12\x18.gateway.RegisterRequest\x1a\x19.gateway.RegisterResponse\" \x82\xd3\xe4\x93\x02\x1a:\x01*\"\x15/api/v1/auth/register\x12U\n" +
	"\x05Login\x12\x15.gateway.LoginRequest\x1a\x16.gateway.LoginResponse\"\x1d\x82\xd3\xe4\x93\x02\x17:\x01*\"\x12/api/v1/auth/login\x12]\n" +
	"\aRefresh\x12\x17.gateway.RefreshRequest\x1a\x18.gateway.RefreshResponse\"\x1f\x82\xd3\xe4\x93\x02\x19:\x01*\"\x14/api/v1/auth/refresh\x12W\n" +
	"\x06Logout\x12\x16.gateway.LogoutRequest\x1a\x15.common.EmptyResponse\"\x1e\x82\xd3\xe4\x93\x02\x18:\x01*\"\x13/api/v1/auth/logout\x12p\n" +
	"\rValidateToken\x12\x1d.gateway.ValidateTokenRequest\x1a\x1e.gateway.ValidateTokenResponse\" \x82\xd3\xe4\x93\x02\x1a:\x01*\"\x15/api/v1/auth/validate\x12Y\n" +
	"\n" +
	"CreateUser\x12\x1a.gateway.CreateUserRequest\x1a\x15.common.EmptyResponse\"\x18\x82\xd3\xe4\x93\x02\x12:\x01*\"\r/api/v1/users\x12]\n" +
	"\aGetUser\x12\x17.gateway.GetUserRequest\x1a\x18.gateway.GetUserResponse\"\x1f\x82\xd3\xe4\x93\x02\x19\x12\x17/api/v1/users/{user_id}\x12a\n" +
	"\x0eGetCurrentUser\x12\x14.common.EmptyRequest\x1a\x1f.gateway.GetCurrentUserResponse\"\x18\x82\xd3\xe4\x93\x02\x12\x12\x10/api/v1/users/me\x12U\n" +
	"\bGetUsers\x12\x18.gateway.GetUsersRequest\x1a\x18.gateway.GetUserResponse\"\x15\x82\xd3\xe4\x93\x02\x0f\x12\r/api/v1/users\x12c\n" +
	"\n" +
	"UpdateUser\x12\x1a.gateway.UpdateUserRequest\x1a\x15.common.EmptyResponse\"\"\x82\xd3\xe4\x93\x02\x1c:\x01*\x1a\x17/api/v1/users/{user_id}\x12j\n" +
	"\x11UpdateCurrentUser\x12!.gateway.UpdateCurrentUserRequest\x1a\x15.common.EmptyResponse\"\x1b\x82\xd3\xe4\x93\x02\x15:\x01*\x1a\x10/api/v1/users/me\x12`\n" +
	"\n" +
	"DeleteUser\x12\x1a.gateway.DeleteUserRequest\x1a\x15.common.EmptyResponse\"\x1f\x82\xd3\xe4\x93\x02\x19*\x17/api/v1/users/{user_id}\x12Z\n" +
	"\x11DeleteCurrentUser\x12\x14.common.EmptyRequest\x1a\x15.common.EmptyResponse\"\x18\x82\xd3\xe4\x93\x02\x12*\x10/api/v1/users/meB-Z+golang_restapi/contracts/gateway/go;gatewayb\x06proto3"

var file_gateway_service_proto_goTypes = []any{
	(*RegisterRequest)(nil),          // 0: gateway.RegisterRequest
	(*LoginRequest)(nil),             // 1: gateway.LoginRequest
	(*RefreshRequest)(nil),           // 2: gateway.RefreshRequest
	(*LogoutRequest)(nil),            // 3: gateway.LogoutRequest
	(*ValidateTokenRequest)(nil),     // 4: gateway.ValidateTokenRequest
	(*CreateUserRequest)(nil),        // 5: gateway.CreateUserRequest
	(*GetUserRequest)(nil),           // 6: gateway.GetUserRequest
	(*_go.EmptyRequest)(nil),         // 7: common.EmptyRequest
	(*GetUsersRequest)(nil),          // 8: gateway.GetUsersRequest
	(*UpdateUserRequest)(nil),        // 9: gateway.UpdateUserRequest
	(*UpdateCurrentUserRequest)(nil), // 10: gateway.UpdateCurrentUserRequest
	(*DeleteUserRequest)(nil),        // 11: gateway.DeleteUserRequest
	(*RegisterResponse)(nil),         // 12: gateway.RegisterResponse
	(*LoginResponse)(nil),            // 13: gateway.LoginResponse
	(*RefreshResponse)(nil),          // 14: gateway.RefreshResponse
	(*_go.EmptyResponse)(nil),        // 15: common.EmptyResponse
	(*ValidateTokenResponse)(nil),    // 16: gateway.ValidateTokenResponse
	(*GetUserResponse)(nil),          // 17: gateway.GetUserResponse
	(*GetCurrentUserResponse)(nil),   // 18: gateway.GetCurrentUserResponse
}
var file_gateway_service_proto_depIdxs = []int32{
	0,  // 0: gateway.Gateway.Register:input_type -> gateway.RegisterRequest
	1,  // 1: gateway.Gateway.Login:input_type -> gateway.LoginRequest
	2,  // 2: gateway.Gateway.Refresh:input_type -> gateway.RefreshRequest
	3,  // 3: gateway.Gateway.Logout:input_type -> gateway.LogoutRequest
	4,  // 4: gateway.Gateway.ValidateToken:input_type -> gateway.ValidateTokenRequest
	5,  // 5: gateway.Gateway.CreateUser:input_type -> gateway.CreateUserRequest
	6,  // 6: gateway.Gateway.GetUser:input_type -> gateway.GetUserRequest
	7,  // 7: gateway.Gateway.GetCurrentUser:input_type -> common.EmptyRequest
	8,  // 8: gateway.Gateway.GetUsers:input_type -> gateway.GetUsersRequest
	9,  // 9: gateway.Gateway.UpdateUser:input_type -> gateway.UpdateUserRequest
	10, // 10: gateway.Gateway.UpdateCurrentUser:input_type -> gateway.UpdateCurrentUserRequest
	11, // 11: gateway.Gateway.DeleteUser:input_type -> gateway.DeleteUserRequest
	7,  // 12: gateway.Gateway.DeleteCurrentUser:input_type -> common.EmptyRequest
	12, // 13: gateway.Gateway.Register:output_type -> gateway.RegisterResponse
	13, // 14: gateway.Gateway.Login:output_type -> gateway.LoginResponse
	14, // 15: gateway.Gateway.Refresh:output_type -> gateway.RefreshResponse
	15, // 16: gateway.Gateway.Logout:output_type -> common.EmptyResponse
	16, // 17: gateway.Gateway.ValidateToken:output_type -> gateway.ValidateTokenResponse
	15, // 18: gateway.Gateway.CreateUser:output_type -> common.EmptyResponse
	17, // 19: gateway.Gateway.GetUser:output_type -> gateway.GetUserResponse
	18, // 20: gateway.Gateway.GetCurrentUser:output_type -> gateway.GetCurrentUserResponse
	17, // 21: gateway.Gateway.GetUsers:output_type -> gateway.GetUserResponse
	15, // 22: gateway.Gateway.UpdateUser:output_type -> common.EmptyResponse
	15, // 23: gateway.Gateway.UpdateCurrentUser:output_type -> common.EmptyResponse
	15, // 24: gateway.Gateway.DeleteUser:output_type -> common.EmptyResponse
	15, // 25: gateway.Gateway.DeleteCurrentUser:output_type -> common.EmptyResponse
	13, // [13:26] is the sub-list for method output_type
	0,  // [0:13] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_gateway_service_proto_init() }
func file_gateway_service_proto_init() {
	if File_gateway_service_proto != nil {
		return
	}
	file_gateway_gateway_model_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gateway_service_proto_rawDesc), len(file_gateway_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_gateway_service_proto_goTypes,
		DependencyIndexes: file_gateway_service_proto_depIdxs,
	}.Build()
	File_gateway_service_proto = out.File
	file_gateway_service_proto_goTypes = nil
	file_gateway_service_proto_depIdxs = nil
}
