services:
  postgres:
    image: postgres:18
    env_file: configs/postgres.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
      - ./deployments/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $${POSTGRES_USER}" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  account:
    build:
      context: .
      dockerfile: deployments/docker/account/Dockerfile
    env_file: configs/account.env
    ports:
      - "50052:50052"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - app-network

  auth:
    build:
      context: .
      dockerfile: deployments/docker/auth/Dockerfile
    env_file: configs/auth.env
    ports:
      - "50051:50051"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - app-network

  gateway:
    build:
      context: .
      dockerfile: deployments/docker/gateway/Dockerfile
    env_file: configs/gateway.env
    ports:
      - "9000:9000"
    depends_on:
      - account
      - auth
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge