syntax = "proto3";
package  account;
option go_package =  "golang_restapi/contracts/account/go;account";

import "google/api/annotations.proto";
import "pagination/pagination.proto";
import "account_model.proto";
import "common/common.proto";

service Account{
  rpc CreateUser(CreateUserRequest) returns(common.EmptyResponse){
    option(google.api.http) = {
      post:"account/api/v1/create_user",
      body:"*"
    };
  }

  rpc GetUser(GetUserRequest) returns (GetUserResponse){
    option(google.api.http) = {
      post:"account/api/v1/users/{user_id}",
      body:"*"
    };
  }

  rpc GetUsers(GetUsersRequest) returns (GetUsersResponse){
    option(google.api.http) = {
      get:"account/api/v1/users"
    };
  }

  rpc DeleteUser(DeleteUserRequest) returns (DeleteUserResponse){
    option(google.api.http) = {
      delete:"account/api/v1/users/{user_id}",
    };
  }

  rpc UpdateUser(UpdateUserRequest) returns (common.EmptyResponse){
    option(google.api.http) = {
      put:"account/api/v1/users/{user_id}",
      body:"*"
    };
  }
}

message CreateUserRequest{
  CreateUser user = 1;}

message GetUserRequest{
  uint64 user_id = 1;
}
message GetUserResponse{
  User user = 1;
}

message GetUsersRequest{
  pagination.Pagination pagination = 1;
}
message GetUsersResponse{
  repeated User users = 1;
  pagination.Pagination pagination = 2;

}

message DeleteUserRequest{
  uint64 user_id = 1;
}
message DeleteUserResponse{
  bool result = 1;
}

message UpdateUserRequest{
  uint64 user_id = 1;
  UpdateUser user = 2;
}

