syntax = "proto3";
package auth;
option go_package = "golang_restapi/contracts/auth/go;auth";

import "common/common.proto";
import "google/api/annotations.proto";

service Auth{
  rpc Register(RegisterRequest) returns (common.EmptyResponse){
    option(google.api.http) = {
      post:"/api/v1/auth/register",
      body:"*"
    };
  };
  rpc Login(LoginRequest) returns (TokenPair){
    option(google.api.http) = {
      post:"/api/v1/auth/login",
      body:"*",
    };
  };

  rpc Refresh(RefreshRequest) returns(TokenPair){
    option(google.api.http) = {
      post: "/api/v1/auth/refresh",
      body:"*"
    };
  };
  rpc ValidateToken(ValidateRequest) returns (ValidateResponse){
    option(google.api.http) = {
      post: "/api/v1/auth/validate",
      body:"*"
    };
  };
  rpc Logout(RefreshRequest) returns(common.EmptyResponse){

    option(google.api.http) = {
      post: "/api/v1/auth/logout",
      body:"*"
    };
  };
}

message RegisterRequest{
  string login = 1;
  string email = 2;
  string password = 3;
}

message LoginRequest{
  string login_or_email = 1;
  string password = 2;
}
message RefreshRequest{
  string refresh_token = 1;
}
message ValidateRequest{
  string access_token = 1;
}
message ValidateResponse{
  int64 user_id = 1;
}
message TokenPair{
  string access_token = 1;
  string refresh_token = 2;
}